'text'={
'caption'={
'pt'={
1='Padrão'
2=1
}
'en'={
1='Default'
}
}
}
'local'={
'document-text-color'='#393a44'
'document-background-color'='#d1d2f9'
'document-border-color'='#048ba8'
'document-header-color'='#048ba8'
'document-link-color'='#893A44'
'document-button-color'='#fff'
'document-button-background-color'='#406e8e'
'document-button-active-color'='#fff'
'document-button-active-background-color'='#393A44'
'panel-background-color'='#cce'
'spotlight-text-color'='#fff'
'spotlight-background-color'='#69c'
'spotlight-link-color'='#fff'
'card-background-color'='#fff'
'formulary-background-color'='#ccc'
'nav-text-color'='#fff'
'nav-background-color'='#000'
'nav-border-color'='#666'
'nav-header-color'='#ccc'
'nav-link-color'='#ccc'
'nav-button-background-color'='transparent'
'nav-button-color'='#fff'
'system-text-color'='#fff'
'system-background-color'='#406e8e'
'system-header-color'='#e80'
'system-link-color'='#e80'
}
