
setTag('ecl-accordion', 'tag_accordion');
setTag('ecl-button', 'tag_button');
setTag('ecl-checkbox', 'tag_checkbox');
setTag('ecl-dialog', 'tag_dialog');
setTag('ecl-file-upload', 'tag_fileUpload');
setTag('ecl-formulary', 'tag_formulary');
setTag('ecl-icon', 'tag_icon');
setTag('ecl-input', 'tag_input');
setTag('ecl-link', 'tag_link');
setTag('ecl-markdown', 'tag_markdown');
setTag('ecl-comal', 'tag_comal');
setTag('ecl-radio', 'tag_radio');
setTag('ecl-select', 'tag_select');
setTag('ecl-tab', 'tag_tab');
setTag('ecl-tab-group', 'tag_tabGroup');
setTag('ecl-text', 'tag_text');
setTag('ecl-textarea', 'tag_textarea');
setTag('gender', 'tag_gender');
