'text'={
'caption'={
'pt'={
1='Canal'
2=1
}
'en'={
1='Channel'
2=1
}
}
}
'local'={
'mod-position'='center'
'wd-sm'='12'
'wd-lg'='12'
'margin-top'='auto'
'margin-right'='auto'
'margin-bottom'='auto'
'margin-left'='auto'
'box-scheme'='card'
'list'='default'
'list-type'='grid'
'list-align'='left'
'col-sm'='1'
'col-lg'='1'
'details'='title_4 media_video description info_posted_elapsed info_owner'
'details-horizontal-spacing'='025'
'details-vertical-spacing'='025'
'img-format'='square'
'list_sort'='created'
'list_direction'='desc'
}
