'text'={
'caption'={
'pt'={
1='Navegação'
2=1
}
'en'={
1='Navigation'
2=1
}
}
}
'local'={
'mod-semantic'='nav'
'mod-padding-top'='0'
'mod-padding-right'='0'
'mod-padding-bottom'='0'
'mod-padding-left'='0'
'wd-sm'='12'
'box-scheme'='nav'
'list-layout'='inline'
'list-align'='center'
'col-sm'='auto'
'list-column-gap'='012'
'list-row-gap'='0012'
'details'='button_caption'
'details-horizontal-align'='center'
'details-vertical-align'='center'
}
